### PR TITLE
New features and some adjustments

### PR DESCRIPTION
**Pull request by noso2k1**
- Added the ability to manage target groups
- Each step of an action checks the status of the task so the action is performed only if necessary. This way actions can be run in sequence
- Description of ToC taken from the description of the task instead of the task number
- Refresh status of a ToC with a button
- Call STMS from the list
- Version of the application as constant in the code (class ZCL_ZABAP_TOC)
- Commented new code adjustments to get ready for a next feature: don't use a selection screen, but rather run with the current user by default and change the filters only once the list is available

### CODE REVIEW

**Comment by noso2k1** [comment]
Hey, I added some features and some adjustments.
I like what you did and it helped me a lot already as it was! But I was missing something important. Since I use this application in an SAP BW environment, very often a release of a ToC takes some time, and when the import starts, the release is not complete. So the main change I did was to check the status before running each step of an action, and performing the step only when necessary. This way I can "create-release" a request, wait for it to be released (I added a refresh status button), and then transport it with the "create-release-transport" button knowing that it will perform only the latter step.
I also changed the "gather_transport" method so it can manage now target groups.
Something I regret committing but I realized too late: I changed the description of the generated Toc, and it's now taken from the task description rather than the task number. This is probably a choice you did for a reason and I shouldn't have overwritten it; sorry for this. I'm thinking of a way to add setting to decide how you want the description to be generated, but it's not done yet.

**Comment by Kaszub09** [comment]
Hey, thanks for taking interest in a project and contributing. :)

As for the changes:
- Version as constant - I think it would be better to do something like https://github.com/abapGit/abapGit/blob/main/src/zif_abapgit_version.intf.abap (and keep version for whole project) than to put version in just one of many classes. I missed this setting in ABAPGIT since I used some older version but I can add it later.
- Description - For me it's just a matter of preference, and ToC [number] is just the way I describe all ToCs on my system. It would probably be better to either have a fork with custom naming scheme or just implement a radio-group at selection-screen with 3 options for description: ToC+Number, Original Description, Ask for description and let user decide.
- Don't use selection screen - I would rather leave selection screen, makes it clear what's selected/with which settings transaction is called. And if you want to skip it, you could always create small program at antoher tcode to cal ZTOC and skip first screen.
- Button to STMS - nice idea, can be included
- Commented new features - I don't think such comments should be included to release version? It's probably better to start implementing them in another branch maybe?
- Target groups - I need to explore this topic, since I have tcetarg rather empty on my system. :P
- Refresh status - I would rather come back to the idea of e.g. unpacking ToCs asynchronously and having 2 seconds timer which runs status check on all ToCs, so you don't have to constantly click manually
- Checking status of task - I may be wrong, but just from reading your code, you don't clear toc_number after refresh? So if I create/release/unpack ToC, refresh status and it's imported, clicking the same button again won't create ToC again, because of check? I would first have to create, and then release? 
- As for the problem of import taking time before release is complete, it sounds like bug to fix rather  than requiring user to release, and then import ToC. I thought cts_api->release blocks execution till release is complete? If not, I think it would be better to simply continue checking in a loop or, as in previous point, implement timer, and then continue with import when release is complete.

Also, I think it would be better to create pull request for each feature - since you can only accept all or nothing, while some changes could be merged, other still require work, so I won't merge it as is.

**Comment by Kaszub09** [comment]
X

**Comment by noso2k1** [comment]
Thanks for taking the time to review the changes and sorry for a big commit; that’s me still learning git workflow.

**Pull request closed without merging**
